import json
from pathlib import Path
from typing import Protocol

from app import (
    BASE_DIR,
    assess_vendor,
    determine_inherent_risk,
    load_controls,
    load_vendor,
)


SYSTEM_PROMPT_FILE = BASE_DIR / "prompts" / "system-prompt.md"
ASSESSMENT_PROMPT_FILE = BASE_DIR / "prompts" / "assessment-prompt.md"
AI_OUTPUT_FILE = BASE_DIR / "outputs" / "ai-assisted-sample.md"


class AssessmentProvider(Protocol):
    """Interface that any approved AI provider must implement."""

    def generate(self, prompt: str) -> str:
        """Generate a draft assessment response."""
        ...


class MockAssessmentProvider:
    """
    Simulates an AI provider for portfolio testing.

    This provider makes no network requests and requires no credentials.
    It must not be represented as a production AI model.
    """

    def generate(self, prompt: str) -> str:
        required_sections = [
            "SYSTEM INSTRUCTIONS",
            "ASSESSMENT INSTRUCTIONS",
            "VENDOR PROFILE",
            "CONTROL LIBRARY",
            "RULES-BASED BASELINE",
        ]

        missing_sections = [
            section for section in required_sections
            if section not in prompt
        ]

        if missing_sections:
            raise ValueError(
                f"Prompt is missing required sections: {missing_sections}"
            )

        return """# Simulated AI-Assisted Assessment

> **Simulation notice:** This output was generated by a mock provider for
> testing and portfolio demonstration. No external AI service was used.

## Executive Summary

NorthStar Analytics presents a preliminary **High inherent risk** because
the service is business-critical and processes personal information and
confidential business data.

The rules-based assessment identified four control gaps. High-risk findings
require validation and approval by an authorized human reviewer.

## Priority Findings

### 1. Independent Penetration Testing

The vendor has not completed an independent penetration test. The stated
120-day implementation commitment is planned remediation and does not
demonstrate that the control currently operates.

**Follow-up evidence request:**

- Independent penetration-test executive summary
- Scope and testing dates
- Severity of identified findings
- Remediation status for high-risk findings

**Human decision required:** Determine whether interim safeguards and the
proposed remediation period sufficiently reduce the engagement risk.

### 2. Endpoint Detection and Response

EDR is not currently deployed. The 30-day commitment must not be treated as
an implemented control.

**Follow-up evidence request:**

- EDR deployment report
- Endpoint coverage percentage
- Detection and response configuration
- Evidence of operational monitoring

**Human decision required:** Determine whether production use should be
restricted until EDR implementation is validated.

### 3. Security Log Retention

The vendor retains security logs for 30 days rather than the required
180-day period.

**Follow-up evidence request:**

- Logging and monitoring policy
- Current platform-retention configuration
- Implementation evidence for 180-day retention

### 4. Subprocessor Risk Management

The vendor reported only partial implementation of its subprocessor-risk
process.

**Follow-up evidence request:**

- Current subprocessor inventory
- Security-review procedure
- Evidence of completed subprocessor assessments
- Customer notification process for material changes

## Preliminary Residual Risk

The preliminary residual-risk rating remains **High** until applicable
high-risk findings are remediated, supporting evidence is validated, and
the authorized risk owner approves the final treatment.

## Human Review Requirements

A qualified reviewer must:

- Validate all referenced evidence
- Confirm control applicability
- Review the severity of each finding
- Approve remediation periods
- Determine whether compensating controls are sufficient
- Make the final vendor-approval and risk-acceptance decisions

## Assumptions and Limitations

- The vendor and assessment data are fictional.
- No evidence was independently authenticated.
- Planned remediation was not treated as implemented.
- This simulated output is not a final risk decision.
"""


def load_prompt_file(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def format_controls(controls: dict) -> str:
    lines = []

    for control_id, control in controls.items():
        lines.append(
            (
                f"- {control_id} | {control['domain']} | "
                f"{control['requirement']} | "
                f"Severity: {control['severity']} | "
                f"Evidence: {control['evidence_expected']}"
            )
        )

    return "\n".join(lines)


def format_baseline(findings: list, inherent_risk: str) -> str:
    lines = [f"Inherent risk: {inherent_risk}"]

    for finding in findings:
        lines.append(
            (
                f"- {finding['control']['control_id']}: "
                f"{finding['title']} | "
                f"Status: {finding['status']} | "
                f"Severity: {finding['severity']}"
            )
        )

    return "\n".join(lines)


def build_assessment_prompt(
    vendor: dict,
    controls: dict,
    findings: list,
    inherent_risk: str,
) -> str:
    system_prompt = load_prompt_file(SYSTEM_PROMPT_FILE)
    assessment_prompt = load_prompt_file(ASSESSMENT_PROMPT_FILE)

    return f"""
SYSTEM INSTRUCTIONS
===================
{system_prompt}

ASSESSMENT INSTRUCTIONS
=======================
{assessment_prompt}

VENDOR PROFILE
==============
{json.dumps(vendor, indent=2)}

CONTROL LIBRARY
===============
{format_controls(controls)}

RULES-BASED BASELINE
====================
{format_baseline(findings, inherent_risk)}

FINAL SAFETY REQUIREMENTS
=========================
- Treat the output as a draft.
- Do not invent evidence.
- Do not approve the vendor.
- Do not accept risk.
- Identify all material human-review decisions.
""".strip()


def run_ai_assessment(provider: AssessmentProvider) -> str:
    vendor = load_vendor()
    controls = load_controls()
    inherent_risk = determine_inherent_risk(vendor)
    findings = assess_vendor(vendor, controls)

    prompt = build_assessment_prompt(
        vendor,
        controls,
        findings,
        inherent_risk,
    )

    response = provider.generate(prompt)

    AI_OUTPUT_FILE.parent.mkdir(exist_ok=True)
    AI_OUTPUT_FILE.write_text(response, encoding="utf-8")

    return str(AI_OUTPUT_FILE)


def main():
    provider = MockAssessmentProvider()
    output_path = run_ai_assessment(provider)

    print(f"Simulated AI assessment completed: {output_path}")


if __name__ == "__main__":
    main()